export const FETCH_EMI_SETTINGS_REQ = "FETCH_EMI_SETTINGS_REQ"
export const FETCH_EMI_SETTINGS_REQ_SUCCESS = "FETCH_EMI_SETTINGS_REQ_SUCCESS"
export const FETCH_EMI_SETTINGS_REQ_FAIL = "FETCH_EMI_SETTINGS_REQ_FAIL"